<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dressly.Domain\Dressly.Domain.csproj" />
    <ProjectReference Include="..\Dressly.Web\Dressly.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.11" />
  </ItemGroup>

</Project>
