// <auto-generated />
using System;
using Dressly.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dressly.Infrastructure.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20260803015842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Dressly.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstatusDonatariaAutorizada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Dressly.Domain.Entities.IdentidadKibbeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionFisica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evitar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LineasNoRecomendadas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LineasRecomendadas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelasSugeridas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEnergia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IdentidadesKibbe");
                });

            modelBuilder.Entity("Dressly.Domain.Entities.Intercambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrendaInteresadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrendaOfertadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioInteresadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioOfertanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Intercambios", (string)null);
                });

            modelBuilder.Entity("Dressly.Domain.Entities.LoteDonacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrendaIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PrendaIdsJson");

                    b.Property<int>("PuntoONGId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuntoONGId");

                    b.ToTable("LotesDonacion", (string)null);
                });

            modelBuilder.Entity("Dressly.Domain.Entities.NegocioPaca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriaPrenda")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Coordenadas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NegociosPaca", (string)null);
                });

            modelBuilder.Entity("Dressly.Domain.Entities.Outfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocasion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrendaIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PrendaIdsJson");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Outfits", (string)null);
                });

            modelBuilder.Entity("Dressly.Domain.Entities.Patrocinio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PuntoONGId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Patrocinios", (string)null);
                });

            modelBuilder.Entity("Dressly.Domain.Entities.Prenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnDesuso")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsDonada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUltimoUso")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VecesUsada")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prendas", (string)null);
                });

            modelBuilder.Entity("Dressly.Domain.Entities.PuntoONG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuntosONG", (string)null);
                });

            modelBuilder.Entity("Dressly.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Dressly.Domain.Entities.LoteDonacion", b =>
                {
                    b.HasOne("Dressly.Domain.Entities.PuntoONG", null)
                        .WithMany()
                        .HasForeignKey("PuntoONGId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dressly.Domain.Entities.Prenda", b =>
                {
                    b.HasOne("Dressly.Domain.Entities.LoteDonacion", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId");

                    b.HasOne("Dressly.Domain.Entities.Usuario", null)
                        .WithMany("Prendas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("Dressly.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("Dressly.Domain.Entities.PerfilFisico", "Perfil", b1 =>
                        {
                            b1.Property<int>("UsuarioId1")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Altura")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ColorOjos")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Colorimetria")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Contraste")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FotoUrl")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("IntensidadCabello")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<int?>("KibbeInfoId")
                                .HasColumnType("INTEGER");

                            b1.Property<double?>("Saturacion")
                                .HasColumnType("REAL");

                            b1.Property<string>("SubtonoPiel")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TipoCuerpo")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TonoPiel")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("UsuarioId1");

                            b1.HasIndex("KibbeInfoId");

                            b1.ToTable("Usuarios");

                            b1.HasOne("Dressly.Domain.Entities.IdentidadKibbeInfo", "KibbeInfo")
                                .WithMany()
                                .HasForeignKey("KibbeInfoId");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId1");

                            b1.Navigation("KibbeInfo");
                        });

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Dressly.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Prendas");
                });
#pragma warning restore 612, 618
        }
    }
}
